# Generated by Django 3.2.4 on 2021-06-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_firstname_userprofile_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
